import sys
with open('src/frontend/FloodCommandCenter.jsx', 'r', encoding='utf-8') as f:
    content = f.read()

new_profiles = open('red_river_profiles.txt', 'w', encoding='utf-8')
new_profiles.write('''const DISTRICT_BASE_PROFILES = [
  {
    district_id: "Shreveport",
    name: "Shreveport",
    river_name: "Red River (Caddo Parish)",
    lat: 32.5149,
    lon: -93.7477,
    shelter_lat: 32.5500,
    shelter_lon: -93.7800,
    hospital_name: "Ochsner LSU Health Shreveport (Emergency Trauma)",
    hospital_lat: 32.4800,
    hospital_lon: -93.7900,
    hospital_icu_capacity: 180,
    hospital_icu_free: 95,
    hospital_status: "🟢 OPERATIONAL (HIGH GROUND)",
    hazard_road: "🚧 I-20 Low-Pass at Cross Lake Submerged (1.2m Water)",
    hazard_lat: 32.5350,
    hazard_lon: -93.7200,
    peak_rain_24h: 165.0,
    peak_water_level: 12.5,
    danger_level: 10.0,
    population_at_risk: 195000,
    nearest_shelter: "Shreveport Convention Center High Ground",
    shelter_capacity: 5200,
    evacuation_route: "I-49 North via Youree Drive Elevated Corridor (14.2 km)",
    evacuation_eta_mins: 24,
    elevation: 57.0,
  },
  {
    district_id: "Texarkana",
    name: "Texarkana",
    river_name: "Sulphur River (Bowie County)",
    lat: 33.4253,
    lon: -94.0477,
    shelter_lat: 33.3900,
    shelter_lon: -94.0200,
    hospital_name: "Christus St. Michael Health System",
    hospital_lat: 33.4100,
    hospital_lon: -94.0600,
    hospital_icu_capacity: 140,
    hospital_icu_free: 42,
    hospital_status: "⚠️ HIGH OCCUPANCY (GENERATOR BACKUP)",
    hazard_road: "🚧 US-59 Low-Lying Bridge Breach (Submerged)",
    hazard_lat: 33.4000,
    hazard_lon: -94.0300,
    peak_rain_24h: 195.0,
    peak_water_level: 14.2,
    danger_level: 11.5,
    population_at_risk: 220000,
    nearest_shelter: "Texarkana College High Ground Complex",
    shelter_capacity: 8500,
    evacuation_route: "US-59 South toward Redwater Ridge Highway (10.1 km)",
    evacuation_eta_mins: 18,
    elevation: 92.0,
  },
  {
    district_id: "Bossier City",
    name: "Bossier City",
    river_name: "Cypress Creek / Red River (Bossier Parish)",
    lat: 32.4335,
    lon: -93.7432,
    shelter_lat: 32.4700,
    shelter_lon: -93.7100,
    hospital_name: "Willis-Knighton South Medical Center",
    hospital_lat: 32.4200,
    hospital_lon: -93.7300,
    hospital_icu_capacity: 130,
    hospital_icu_free: 55,
    hospital_status: "🟢 OPERATIONAL",
    hazard_road: "🚧 Cypress Creek Causeway Overflow",
    hazard_lat: 32.4500,
    hazard_lon: -93.7500,
    peak_rain_24h: 175.0,
    peak_water_level: 11.8,
    danger_level: 9.8,
    population_at_risk: 155000,
    nearest_shelter: "Bossier Civic Center High Ground",
    shelter_capacity: 4800,
    evacuation_route: "LA-511 Bypass via Airline Drive Highway (11.5 km)",
    evacuation_eta_mins: 21,
    elevation: 48.0,
  },
  {
    district_id: "Mansfield",
    name: "Mansfield",
    river_name: "Little River (DeSoto Parish)",
    lat: 32.0365,
    lon: -93.6977,
    shelter_lat: 32.0800,
    shelter_lon: -93.6500,
    hospital_name: "DeSoto Regional Health System Emergency Wing",
    hospital_lat: 32.0300,
    hospital_lon: -93.6800,
    hospital_icu_capacity: 160,
    hospital_icu_free: 72,
    hospital_status: "🟢 OPERATIONAL",
    hazard_road: "🚧 Little River Embankment Road Breached",
    hazard_lat: 32.0600,
    hazard_lon: -93.7100,
    peak_rain_24h: 130.0,
    peak_water_level: 8.2,
    danger_level: 7.0,
    population_at_risk: 98000,
    nearest_shelter: "Mansfield High School Shelter",
    shelter_capacity: 3200,
    evacuation_route: "US-171 East toward Stonewall (16.3 km)",
    evacuation_eta_mins: 28,
    elevation: 85.0,
  },
  {
    district_id: "Coushatta",
    name: "Coushatta",
    river_name: "Red River North Fork (Red River Parish)",
    lat: 31.9977,
    lon: -93.3369,
    shelter_lat: 32.0200,
    shelter_lon: -93.3000,
    hospital_name: "Red River Parish Medical Center",
    hospital_lat: 31.9900,
    hospital_lon: -93.3400,
    hospital_icu_capacity: 85,
    hospital_icu_free: 28,
    hospital_status: "🟢 OPERATIONAL",
    hazard_road: "🚧 Red River Bridge Low Approach Blocked",
    hazard_lat: 32.0100,
    hazard_lon: -93.3200,
    peak_rain_24h: 150.0,
    peak_water_level: 9.5,
    danger_level: 8.2,
    population_at_risk: 115000,
    nearest_shelter: "Coushatta Town Hall Shelter",
    shelter_capacity: 3600,
    evacuation_route: "US-371 South via Martin Road (12.8 km)",
    evacuation_eta_mins: 20,
    elevation: 42.0,
  },
  {
    district_id: "Mount Pleasant",
    name: "Mount Pleasant",
    river_name: "Sulphur River East Fork (Titus County)",
    lat: 33.1562,
    lon: -94.9686,
    shelter_lat: 33.2000,
    shelter_lon: -94.9400,
    hospital_name: "Mount Pleasant Regional Hospital Sub-Divisional",
    hospital_lat: 33.1500,
    hospital_lon: -94.9700,
    hospital_icu_capacity: 95,
    hospital_icu_free: 38,
    hospital_status: "🟢 OPERATIONAL",
    hazard_road: "🚧 Sulphur Canal Feeder Road Inundated",
    hazard_lat: 33.1700,
    hazard_lon: -94.9500,
    peak_rain_24h: 115.0,
    peak_water_level: 7.5,
    danger_level: 6.8,
    population_at_risk: 68000,
    nearest_shelter: "Mount Pleasant Community Center",
    shelter_capacity: 2600,
    evacuation_route: "TX-49 East towards Talco (15.5 km)",
    evacuation_eta_mins: 23,
    elevation: 110.0,
  },
  {
    district_id: "Linden",
    name: "Linden",
    river_name: "Cypress Creek (Cass County)",
    lat: 33.0025,
    lon: -94.3707,
    shelter_lat: 33.0500,
    shelter_lon: -94.3400,
    hospital_name: "Linden County Hospital",
    hospital_lat: 32.9900,
    hospital_lon: -94.3600,
    hospital_icu_capacity: 110,
    hospital_icu_free: 58,
    hospital_status: "🟢 OPERATIONAL",
    hazard_road: "🚧 TX-8 Railway Underpass Flooded",
    hazard_lat: 33.0200,
    hazard_lon: -94.3800,
    peak_rain_24h: 90.0,
    peak_water_level: 6.2,
    danger_level: 5.5,
    population_at_risk: 45000,
    nearest_shelter: "Linden Civic Sports Complex",
    shelter_capacity: 3100,
    evacuation_route: "US-59 North Bypass (7.8 km)",
    evacuation_eta_mins: 14,
    elevation: 78.0,
  },
  {
    district_id: "Hope",
    name: "Hope",
    river_name: "Red River South Fork (Hempstead County)",
    lat: 33.6675,
    lon: -93.5916,
    shelter_lat: 33.7000,
    shelter_lon: -93.5600,
    hospital_name: "Hope Medical Center Emergency Trauma",
    hospital_lat: 33.6600,
    hospital_lon: -93.5800,
    hospital_icu_capacity: 150,
    hospital_icu_free: 82,
    hospital_status: "🟢 OPERATIONAL",
    hazard_road: "🚧 Red River Embankment South Road Caution",
    hazard_lat: 33.6900,
    hazard_lon: -93.6000,
    peak_rain_24h: 80.0,
    peak_water_level: 5.8,
    danger_level: 5.0,
    population_at_risk: 30000,
    nearest_shelter: "Hope Convention Center High Ground",
    shelter_capacity: 4200,
    evacuation_route: "I-30 East (9.2 km)",
    evacuation_eta_mins: 16,
    elevation: 65.0,
  },
];''')
new_profiles.close()

start_marker = 'const DISTRICT_BASE_PROFILES = ['
start_idx = content.find(start_marker)
end_marker = '\n// Helper to compute risk-proportionate shelter occupancy'
end_idx = content.find(end_marker, start_idx)

with open('red_river_profiles.txt', 'r', encoding='utf-8') as f:
    profiles_text = f.read()

if start_idx != -1 and end_idx != -1:
    content = content[:start_idx] + profiles_text + '\n' + content[end_idx:]
    with open('src/frontend/FloodCommandCenter.jsx', 'w', encoding='utf-8') as f:
        f.write(content)
    print('Profiles replaced successfully.')
else:
    print('Failed to find markers:', start_idx, end_idx)
